// Generated by jextract

package org.linux;

import java.lang.invoke.*;
import java.lang.foreign.*;

import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct dirent {
 *     __ino_t d_ino;
 *     __off_t d_off;
 *     unsigned short d_reclen;
 *     unsigned char d_type;
 *     char d_name[256];
 * }
 * }
 */
@SuppressWarnings("all")
public class dirent {

    dirent() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        LibC.C_LONG.withName("d_ino"),
        LibC.C_LONG.withName("d_off"),
        LibC.C_SHORT.withName("d_reclen"),
        LibC.C_CHAR.withName("d_type"),
        MemoryLayout.sequenceLayout(256, LibC.C_CHAR).withName("d_name"),
        MemoryLayout.paddingLayout(5)
    ).withName("dirent");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout d_name$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("d_name"));

    private static final long d_name$OFFSET = $LAYOUT.byteOffset(groupElement("d_name"));

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char d_name[256]
     * }
     */
    public static MemorySegment d_name(MemorySegment struct) {
        return struct.asSlice(d_name$OFFSET, d_name$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char d_name[256]
     * }
     */
    public static void d_name(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, d_name$OFFSET, d_name$LAYOUT.byteSize());
    }

    private static final VarHandle d_name$ELEM_HANDLE = d_name$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char d_name[256]
     * }
     */
    public static byte d_name(MemorySegment struct, long index0) {
        return (byte)d_name$ELEM_HANDLE.get(struct, d_name$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char d_name[256]
     * }
     */
    public static void d_name(MemorySegment struct, long index0, byte fieldValue) {
        d_name$ELEM_HANDLE.set(struct, d_name$OFFSET, index0, fieldValue);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

}

