// Generated by jextract

package org.linux;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class LibC extends LibC$shared {

    LibC() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    private static final int PATH_MAX = (int)4096L;
    /**
     * {@snippet lang=c :
     * #define PATH_MAX 4096
     * }
     */
    public static int PATH_MAX() {
        return PATH_MAX;
    }
    private static final int ENOENT = (int)2L;
    /**
     * {@snippet lang=c :
     * #define ENOENT 2
     * }
     */
    public static int ENOENT() {
        return ENOENT;
    }
    private static final int AT_SYMLINK_NOFOLLOW = (int)256L;
    /**
     * {@snippet lang=c :
     * #define AT_SYMLINK_NOFOLLOW 256
     * }
     */
    public static int AT_SYMLINK_NOFOLLOW() {
        return AT_SYMLINK_NOFOLLOW;
    }
    private static final int AT_STATX_SYNC_AS_STAT = (int)0L;
    /**
     * {@snippet lang=c :
     * #define AT_STATX_SYNC_AS_STAT 0
     * }
     */
    public static int AT_STATX_SYNC_AS_STAT() {
        return AT_STATX_SYNC_AS_STAT;
    }

    private static class closedir {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            LibC.C_INT,
            LibC.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("closedir");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern int closedir(DIR *__dirp)
     * }
     */
    public static FunctionDescriptor closedir$descriptor() {
        return closedir.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern int closedir(DIR *__dirp)
     * }
     */
    public static MethodHandle closedir$handle() {
        return closedir.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern int closedir(DIR *__dirp)
     * }
     */
    public static MemorySegment closedir$address() {
        return closedir.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern int closedir(DIR *__dirp)
     * }
     */
    public static int closedir(MemorySegment __dirp) {
        var mh$ = closedir.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("closedir", __dirp);
            }
            return (int)mh$.invokeExact(__dirp);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class opendir {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            LibC.C_POINTER,
            LibC.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("opendir");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern DIR *opendir(const char *__name)
     * }
     */
    public static FunctionDescriptor opendir$descriptor() {
        return opendir.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern DIR *opendir(const char *__name)
     * }
     */
    public static MethodHandle opendir$handle() {
        return opendir.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern DIR *opendir(const char *__name)
     * }
     */
    public static MemorySegment opendir$address() {
        return opendir.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern DIR *opendir(const char *__name)
     * }
     */
    public static MemorySegment opendir(MemorySegment __name) {
        var mh$ = opendir.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("opendir", __name);
            }
            return (MemorySegment)mh$.invokeExact(__name);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class readdir {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            LibC.C_POINTER,
            LibC.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("readdir");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern struct dirent *readdir(DIR *__dirp)
     * }
     */
    public static FunctionDescriptor readdir$descriptor() {
        return readdir.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern struct dirent *readdir(DIR *__dirp)
     * }
     */
    public static MethodHandle readdir$handle() {
        return readdir.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern struct dirent *readdir(DIR *__dirp)
     * }
     */
    public static MemorySegment readdir$address() {
        return readdir.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern struct dirent *readdir(DIR *__dirp)
     * }
     */
    public static MemorySegment readdir(MemorySegment __dirp) {
        var mh$ = readdir.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("readdir", __dirp);
            }
            return (MemorySegment)mh$.invokeExact(__dirp);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class dirfd {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            LibC.C_INT,
            LibC.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("dirfd");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern int dirfd(DIR *__dirp)
     * }
     */
    public static FunctionDescriptor dirfd$descriptor() {
        return dirfd.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern int dirfd(DIR *__dirp)
     * }
     */
    public static MethodHandle dirfd$handle() {
        return dirfd.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern int dirfd(DIR *__dirp)
     * }
     */
    public static MemorySegment dirfd$address() {
        return dirfd.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern int dirfd(DIR *__dirp)
     * }
     */
    public static int dirfd(MemorySegment __dirp) {
        var mh$ = dirfd.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("dirfd", __dirp);
            }
            return (int)mh$.invokeExact(__dirp);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class chmod {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            LibC.C_INT,
            LibC.C_POINTER,
            LibC.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("chmod");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern int chmod(const char *__file, __mode_t __mode)
     * }
     */
    public static FunctionDescriptor chmod$descriptor() {
        return chmod.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern int chmod(const char *__file, __mode_t __mode)
     * }
     */
    public static MethodHandle chmod$handle() {
        return chmod.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern int chmod(const char *__file, __mode_t __mode)
     * }
     */
    public static MemorySegment chmod$address() {
        return chmod.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern int chmod(const char *__file, __mode_t __mode)
     * }
     */
    public static int chmod(MemorySegment __file, int __mode) {
        var mh$ = chmod.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("chmod", __file, __mode);
            }
            return (int)mh$.invokeExact(__file, __mode);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class statx {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            LibC.C_INT,
            LibC.C_INT,
            LibC.C_POINTER,
            LibC.C_INT,
            LibC.C_INT,
            LibC.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("statx");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int statx(int __dirfd, const char *restrict __path, int __flags, unsigned int __mask, struct statx *restrict __buf)
     * }
     */
    public static FunctionDescriptor statx$descriptor() {
        return statx.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int statx(int __dirfd, const char *restrict __path, int __flags, unsigned int __mask, struct statx *restrict __buf)
     * }
     */
    public static MethodHandle statx$handle() {
        return statx.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int statx(int __dirfd, const char *restrict __path, int __flags, unsigned int __mask, struct statx *restrict __buf)
     * }
     */
    public static MemorySegment statx$address() {
        return statx.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int statx(int __dirfd, const char *restrict __path, int __flags, unsigned int __mask, struct statx *restrict __buf)
     * }
     */
    public static int statx(int __dirfd, MemorySegment __path, int __flags, int __mask, MemorySegment __buf) {
        var mh$ = statx.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("statx", __dirfd, __path, __flags, __mask, __buf);
            }
            return (int)mh$.invokeExact(__dirfd, __path, __flags, __mask, __buf);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class readlinkat {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            LibC.C_LONG,
            LibC.C_INT,
            LibC.C_POINTER,
            LibC.C_POINTER,
            LibC.C_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("readlinkat");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern ssize_t readlinkat(int __fd, const char *restrict __path, char *restrict __buf, size_t __len)
     * }
     */
    public static FunctionDescriptor readlinkat$descriptor() {
        return readlinkat.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern ssize_t readlinkat(int __fd, const char *restrict __path, char *restrict __buf, size_t __len)
     * }
     */
    public static MethodHandle readlinkat$handle() {
        return readlinkat.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern ssize_t readlinkat(int __fd, const char *restrict __path, char *restrict __buf, size_t __len)
     * }
     */
    public static MemorySegment readlinkat$address() {
        return readlinkat.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern ssize_t readlinkat(int __fd, const char *restrict __path, char *restrict __buf, size_t __len)
     * }
     */
    public static long readlinkat(int __fd, MemorySegment __path, MemorySegment __buf, long __len) {
        var mh$ = readlinkat.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("readlinkat", __fd, __path, __buf, __len);
            }
            return (long)mh$.invokeExact(__fd, __path, __buf, __len);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final int S_IFMT = (int)61440L;
    /**
     * {@snippet lang=c :
     * #define S_IFMT 61440
     * }
     */
    public static int S_IFMT() {
        return S_IFMT;
    }
    private static final int S_IFDIR = (int)16384L;
    /**
     * {@snippet lang=c :
     * #define S_IFDIR 16384
     * }
     */
    public static int S_IFDIR() {
        return S_IFDIR;
    }
    private static final int S_IFLNK = (int)40960L;
    /**
     * {@snippet lang=c :
     * #define S_IFLNK 40960
     * }
     */
    public static int S_IFLNK() {
        return S_IFLNK;
    }
    private static final int S_IRUSR = (int)256L;
    /**
     * {@snippet lang=c :
     * #define S_IRUSR 256
     * }
     */
    public static int S_IRUSR() {
        return S_IRUSR;
    }
    private static final int S_IWUSR = (int)128L;
    /**
     * {@snippet lang=c :
     * #define S_IWUSR 128
     * }
     */
    public static int S_IWUSR() {
        return S_IWUSR;
    }
    private static final int S_IXUSR = (int)64L;
    /**
     * {@snippet lang=c :
     * #define S_IXUSR 64
     * }
     */
    public static int S_IXUSR() {
        return S_IXUSR;
    }
    private static final int S_IRGRP = (int)32L;
    /**
     * {@snippet lang=c :
     * #define S_IRGRP 32
     * }
     */
    public static int S_IRGRP() {
        return S_IRGRP;
    }
    private static final int S_IWGRP = (int)16L;
    /**
     * {@snippet lang=c :
     * #define S_IWGRP 16
     * }
     */
    public static int S_IWGRP() {
        return S_IWGRP;
    }
    private static final int S_IXGRP = (int)8L;
    /**
     * {@snippet lang=c :
     * #define S_IXGRP 8
     * }
     */
    public static int S_IXGRP() {
        return S_IXGRP;
    }
    private static final int S_IROTH = (int)4L;
    /**
     * {@snippet lang=c :
     * #define S_IROTH 4
     * }
     */
    public static int S_IROTH() {
        return S_IROTH;
    }
    private static final int S_IWOTH = (int)2L;
    /**
     * {@snippet lang=c :
     * #define S_IWOTH 2
     * }
     */
    public static int S_IWOTH() {
        return S_IWOTH;
    }
    private static final int S_IXOTH = (int)1L;
    /**
     * {@snippet lang=c :
     * #define S_IXOTH 1
     * }
     */
    public static int S_IXOTH() {
        return S_IXOTH;
    }
    private static final int AT_FDCWD = (int)-100L;
    /**
     * {@snippet lang=c :
     * #define AT_FDCWD -100
     * }
     */
    public static int AT_FDCWD() {
        return AT_FDCWD;
    }
    private static final int STATX_TYPE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define STATX_TYPE 1
     * }
     */
    public static int STATX_TYPE() {
        return STATX_TYPE;
    }
    private static final int STATX_MODE = (int)2L;
    /**
     * {@snippet lang=c :
     * #define STATX_MODE 2
     * }
     */
    public static int STATX_MODE() {
        return STATX_MODE;
    }
    private static final int STATX_MTIME = (int)64L;
    /**
     * {@snippet lang=c :
     * #define STATX_MTIME 64
     * }
     */
    public static int STATX_MTIME() {
        return STATX_MTIME;
    }
    private static final int STATX_SIZE = (int)512L;
    /**
     * {@snippet lang=c :
     * #define STATX_SIZE 512
     * }
     */
    public static int STATX_SIZE() {
        return STATX_SIZE;
    }
}

