// Generated by jextract

package org.linux;

import java.lang.foreign.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct statx_timestamp {
 *     __s64 tv_sec;
 *     __u32 tv_nsec;
 *     __s32 __reserved;
 * }
 * }
 */
@SuppressWarnings("all")
public class statx_timestamp {

    statx_timestamp() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        LibC.C_LONG_LONG.withName("tv_sec"),
        LibC.C_INT.withName("tv_nsec"),
        LibC.C_INT.withName("__reserved")
    ).withName("statx_timestamp");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong tv_sec$LAYOUT = (OfLong)$LAYOUT.select(groupElement("tv_sec"));

    private static final long tv_sec$OFFSET = $LAYOUT.byteOffset(groupElement("tv_sec"));

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __s64 tv_sec
     * }
     */
    public static long tv_sec(MemorySegment struct) {
        return struct.get(tv_sec$LAYOUT, tv_sec$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __s64 tv_sec
     * }
     */
    public static void tv_sec(MemorySegment struct, long fieldValue) {
        struct.set(tv_sec$LAYOUT, tv_sec$OFFSET, fieldValue);
    }

    private static final OfInt tv_nsec$LAYOUT = (OfInt)$LAYOUT.select(groupElement("tv_nsec"));

    private static final long tv_nsec$OFFSET = $LAYOUT.byteOffset(groupElement("tv_nsec"));

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 tv_nsec
     * }
     */
    public static int tv_nsec(MemorySegment struct) {
        return struct.get(tv_nsec$LAYOUT, tv_nsec$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 tv_nsec
     * }
     */
    public static void tv_nsec(MemorySegment struct, int fieldValue) {
        struct.set(tv_nsec$LAYOUT, tv_nsec$OFFSET, fieldValue);
    }

}

