// Generated by jextract

package org.linux;

import java.lang.foreign.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct statx {
 *     __u32 stx_mask;
 *     __u32 stx_blksize;
 *     __u64 stx_attributes;
 *     __u32 stx_nlink;
 *     __u32 stx_uid;
 *     __u32 stx_gid;
 *     __u16 stx_mode;
 *     __u16 __spare0[1];
 *     __u64 stx_ino;
 *     __u64 stx_size;
 *     __u64 stx_blocks;
 *     __u64 stx_attributes_mask;
 *     struct statx_timestamp stx_atime;
 *     struct statx_timestamp stx_btime;
 *     struct statx_timestamp stx_ctime;
 *     struct statx_timestamp stx_mtime;
 *     __u32 stx_rdev_major;
 *     __u32 stx_rdev_minor;
 *     __u32 stx_dev_major;
 *     __u32 stx_dev_minor;
 *     __u64 stx_mnt_id;
 *     __u32 stx_dio_mem_align;
 *     __u32 stx_dio_offset_align;
 *     __u64 stx_subvol;
 *     __u32 stx_atomic_write_unit_min;
 *     __u32 stx_atomic_write_unit_max;
 *     __u32 stx_atomic_write_segments_max;
 *     __u32 stx_dio_read_offset_align;
 *     __u32 stx_atomic_write_unit_max_opt;
 *     __u32 __spare2[1];
 *     __u64 __spare3[8];
 * }
 * }
 */
@SuppressWarnings("all")
public class statx {

    statx() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        LibC.C_INT.withName("stx_mask"),
        LibC.C_INT.withName("stx_blksize"),
        LibC.C_LONG_LONG.withName("stx_attributes"),
        LibC.C_INT.withName("stx_nlink"),
        LibC.C_INT.withName("stx_uid"),
        LibC.C_INT.withName("stx_gid"),
        LibC.C_SHORT.withName("stx_mode"),
        MemoryLayout.sequenceLayout(1, LibC.C_SHORT).withName("__spare0"),
        LibC.C_LONG_LONG.withName("stx_ino"),
        LibC.C_LONG_LONG.withName("stx_size"),
        LibC.C_LONG_LONG.withName("stx_blocks"),
        LibC.C_LONG_LONG.withName("stx_attributes_mask"),
        statx_timestamp.layout().withName("stx_atime"),
        statx_timestamp.layout().withName("stx_btime"),
        statx_timestamp.layout().withName("stx_ctime"),
        statx_timestamp.layout().withName("stx_mtime"),
        LibC.C_INT.withName("stx_rdev_major"),
        LibC.C_INT.withName("stx_rdev_minor"),
        LibC.C_INT.withName("stx_dev_major"),
        LibC.C_INT.withName("stx_dev_minor"),
        LibC.C_LONG_LONG.withName("stx_mnt_id"),
        LibC.C_INT.withName("stx_dio_mem_align"),
        LibC.C_INT.withName("stx_dio_offset_align"),
        LibC.C_LONG_LONG.withName("stx_subvol"),
        LibC.C_INT.withName("stx_atomic_write_unit_min"),
        LibC.C_INT.withName("stx_atomic_write_unit_max"),
        LibC.C_INT.withName("stx_atomic_write_segments_max"),
        LibC.C_INT.withName("stx_dio_read_offset_align"),
        LibC.C_INT.withName("stx_atomic_write_unit_max_opt"),
        MemoryLayout.sequenceLayout(1, LibC.C_INT).withName("__spare2"),
        MemoryLayout.sequenceLayout(8, LibC.C_LONG_LONG).withName("__spare3")
    ).withName("statx");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfShort stx_mode$LAYOUT = (OfShort)$LAYOUT.select(groupElement("stx_mode"));

    private static final long stx_mode$OFFSET = $LAYOUT.byteOffset(groupElement("stx_mode"));

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u16 stx_mode
     * }
     */
    public static short stx_mode(MemorySegment struct) {
        return struct.get(stx_mode$LAYOUT, stx_mode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u16 stx_mode
     * }
     */
    public static void stx_mode(MemorySegment struct, short fieldValue) {
        struct.set(stx_mode$LAYOUT, stx_mode$OFFSET, fieldValue);
    }

    private static final OfLong stx_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("stx_size"));

    private static final long stx_size$OFFSET = $LAYOUT.byteOffset(groupElement("stx_size"));

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 stx_size
     * }
     */
    public static long stx_size(MemorySegment struct) {
        return struct.get(stx_size$LAYOUT, stx_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 stx_size
     * }
     */
    public static void stx_size(MemorySegment struct, long fieldValue) {
        struct.set(stx_size$LAYOUT, stx_size$OFFSET, fieldValue);
    }

    private static final GroupLayout stx_mtime$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("stx_mtime"));

    private static final long stx_mtime$OFFSET = $LAYOUT.byteOffset(groupElement("stx_mtime"));

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct statx_timestamp stx_mtime
     * }
     */
    public static MemorySegment stx_mtime(MemorySegment struct) {
        return struct.asSlice(stx_mtime$OFFSET, stx_mtime$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct statx_timestamp stx_mtime
     * }
     */
    public static void stx_mtime(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, stx_mtime$OFFSET, stx_mtime$LAYOUT.byteSize());
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

}

