// Generated by jextract

package org.linux;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct statx {
 *     __u32 stx_mask;
 *     __u32 stx_blksize;
 *     __u64 stx_attributes;
 *     __u32 stx_nlink;
 *     __u32 stx_uid;
 *     __u32 stx_gid;
 *     __u16 stx_mode;
 *     __u16 __spare0[1];
 *     __u64 stx_ino;
 *     __u64 stx_size;
 *     __u64 stx_blocks;
 *     __u64 stx_attributes_mask;
 *     struct statx_timestamp stx_atime;
 *     struct statx_timestamp stx_btime;
 *     struct statx_timestamp stx_ctime;
 *     struct statx_timestamp stx_mtime;
 *     __u32 stx_rdev_major;
 *     __u32 stx_rdev_minor;
 *     __u32 stx_dev_major;
 *     __u32 stx_dev_minor;
 *     __u64 stx_mnt_id;
 *     __u32 stx_dio_mem_align;
 *     __u32 stx_dio_offset_align;
 *     __u64 stx_subvol;
 *     __u32 stx_atomic_write_unit_min;
 *     __u32 stx_atomic_write_unit_max;
 *     __u32 stx_atomic_write_segments_max;
 *     __u32 stx_dio_read_offset_align;
 *     __u32 stx_atomic_write_unit_max_opt;
 *     __u32 __spare2[1];
 *     __u64 __spare3[8];
 * }
 * }
 */
public class statx {

    statx() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        LibC.C_INT.withName("stx_mask"),
        LibC.C_INT.withName("stx_blksize"),
        LibC.C_LONG_LONG.withName("stx_attributes"),
        LibC.C_INT.withName("stx_nlink"),
        LibC.C_INT.withName("stx_uid"),
        LibC.C_INT.withName("stx_gid"),
        LibC.C_SHORT.withName("stx_mode"),
        MemoryLayout.sequenceLayout(1, LibC.C_SHORT).withName("__spare0"),
        LibC.C_LONG_LONG.withName("stx_ino"),
        LibC.C_LONG_LONG.withName("stx_size"),
        LibC.C_LONG_LONG.withName("stx_blocks"),
        LibC.C_LONG_LONG.withName("stx_attributes_mask"),
        statx_timestamp.layout().withName("stx_atime"),
        statx_timestamp.layout().withName("stx_btime"),
        statx_timestamp.layout().withName("stx_ctime"),
        statx_timestamp.layout().withName("stx_mtime"),
        LibC.C_INT.withName("stx_rdev_major"),
        LibC.C_INT.withName("stx_rdev_minor"),
        LibC.C_INT.withName("stx_dev_major"),
        LibC.C_INT.withName("stx_dev_minor"),
        LibC.C_LONG_LONG.withName("stx_mnt_id"),
        LibC.C_INT.withName("stx_dio_mem_align"),
        LibC.C_INT.withName("stx_dio_offset_align"),
        LibC.C_LONG_LONG.withName("stx_subvol"),
        LibC.C_INT.withName("stx_atomic_write_unit_min"),
        LibC.C_INT.withName("stx_atomic_write_unit_max"),
        LibC.C_INT.withName("stx_atomic_write_segments_max"),
        LibC.C_INT.withName("stx_dio_read_offset_align"),
        LibC.C_INT.withName("stx_atomic_write_unit_max_opt"),
        MemoryLayout.sequenceLayout(1, LibC.C_INT).withName("__spare2"),
        MemoryLayout.sequenceLayout(8, LibC.C_LONG_LONG).withName("__spare3")
    ).withName("statx");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt stx_mask$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stx_mask"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 stx_mask
     * }
     */
    public static final OfInt stx_mask$layout() {
        return stx_mask$LAYOUT;
    }

    private static final long stx_mask$OFFSET = $LAYOUT.byteOffset(groupElement("stx_mask"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 stx_mask
     * }
     */
    public static final long stx_mask$offset() {
        return stx_mask$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 stx_mask
     * }
     */
    public static int stx_mask(MemorySegment struct) {
        return struct.get(stx_mask$LAYOUT, stx_mask$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 stx_mask
     * }
     */
    public static void stx_mask(MemorySegment struct, int fieldValue) {
        struct.set(stx_mask$LAYOUT, stx_mask$OFFSET, fieldValue);
    }

    private static final OfInt stx_blksize$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stx_blksize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 stx_blksize
     * }
     */
    public static final OfInt stx_blksize$layout() {
        return stx_blksize$LAYOUT;
    }

    private static final long stx_blksize$OFFSET = $LAYOUT.byteOffset(groupElement("stx_blksize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 stx_blksize
     * }
     */
    public static final long stx_blksize$offset() {
        return stx_blksize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 stx_blksize
     * }
     */
    public static int stx_blksize(MemorySegment struct) {
        return struct.get(stx_blksize$LAYOUT, stx_blksize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 stx_blksize
     * }
     */
    public static void stx_blksize(MemorySegment struct, int fieldValue) {
        struct.set(stx_blksize$LAYOUT, stx_blksize$OFFSET, fieldValue);
    }

    private static final OfLong stx_attributes$LAYOUT = (OfLong)$LAYOUT.select(groupElement("stx_attributes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 stx_attributes
     * }
     */
    public static final OfLong stx_attributes$layout() {
        return stx_attributes$LAYOUT;
    }

    private static final long stx_attributes$OFFSET = $LAYOUT.byteOffset(groupElement("stx_attributes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 stx_attributes
     * }
     */
    public static final long stx_attributes$offset() {
        return stx_attributes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 stx_attributes
     * }
     */
    public static long stx_attributes(MemorySegment struct) {
        return struct.get(stx_attributes$LAYOUT, stx_attributes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 stx_attributes
     * }
     */
    public static void stx_attributes(MemorySegment struct, long fieldValue) {
        struct.set(stx_attributes$LAYOUT, stx_attributes$OFFSET, fieldValue);
    }

    private static final OfInt stx_nlink$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stx_nlink"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 stx_nlink
     * }
     */
    public static final OfInt stx_nlink$layout() {
        return stx_nlink$LAYOUT;
    }

    private static final long stx_nlink$OFFSET = $LAYOUT.byteOffset(groupElement("stx_nlink"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 stx_nlink
     * }
     */
    public static final long stx_nlink$offset() {
        return stx_nlink$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 stx_nlink
     * }
     */
    public static int stx_nlink(MemorySegment struct) {
        return struct.get(stx_nlink$LAYOUT, stx_nlink$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 stx_nlink
     * }
     */
    public static void stx_nlink(MemorySegment struct, int fieldValue) {
        struct.set(stx_nlink$LAYOUT, stx_nlink$OFFSET, fieldValue);
    }

    private static final OfInt stx_uid$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stx_uid"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 stx_uid
     * }
     */
    public static final OfInt stx_uid$layout() {
        return stx_uid$LAYOUT;
    }

    private static final long stx_uid$OFFSET = $LAYOUT.byteOffset(groupElement("stx_uid"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 stx_uid
     * }
     */
    public static final long stx_uid$offset() {
        return stx_uid$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 stx_uid
     * }
     */
    public static int stx_uid(MemorySegment struct) {
        return struct.get(stx_uid$LAYOUT, stx_uid$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 stx_uid
     * }
     */
    public static void stx_uid(MemorySegment struct, int fieldValue) {
        struct.set(stx_uid$LAYOUT, stx_uid$OFFSET, fieldValue);
    }

    private static final OfInt stx_gid$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stx_gid"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 stx_gid
     * }
     */
    public static final OfInt stx_gid$layout() {
        return stx_gid$LAYOUT;
    }

    private static final long stx_gid$OFFSET = $LAYOUT.byteOffset(groupElement("stx_gid"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 stx_gid
     * }
     */
    public static final long stx_gid$offset() {
        return stx_gid$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 stx_gid
     * }
     */
    public static int stx_gid(MemorySegment struct) {
        return struct.get(stx_gid$LAYOUT, stx_gid$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 stx_gid
     * }
     */
    public static void stx_gid(MemorySegment struct, int fieldValue) {
        struct.set(stx_gid$LAYOUT, stx_gid$OFFSET, fieldValue);
    }

    private static final OfShort stx_mode$LAYOUT = (OfShort)$LAYOUT.select(groupElement("stx_mode"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u16 stx_mode
     * }
     */
    public static final OfShort stx_mode$layout() {
        return stx_mode$LAYOUT;
    }

    private static final long stx_mode$OFFSET = $LAYOUT.byteOffset(groupElement("stx_mode"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u16 stx_mode
     * }
     */
    public static final long stx_mode$offset() {
        return stx_mode$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u16 stx_mode
     * }
     */
    public static short stx_mode(MemorySegment struct) {
        return struct.get(stx_mode$LAYOUT, stx_mode$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u16 stx_mode
     * }
     */
    public static void stx_mode(MemorySegment struct, short fieldValue) {
        struct.set(stx_mode$LAYOUT, stx_mode$OFFSET, fieldValue);
    }

    private static final SequenceLayout __spare0$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("__spare0"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u16 __spare0[1]
     * }
     */
    public static final SequenceLayout __spare0$layout() {
        return __spare0$LAYOUT;
    }

    private static final long __spare0$OFFSET = $LAYOUT.byteOffset(groupElement("__spare0"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u16 __spare0[1]
     * }
     */
    public static final long __spare0$offset() {
        return __spare0$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u16 __spare0[1]
     * }
     */
    public static MemorySegment __spare0(MemorySegment struct) {
        return struct.asSlice(__spare0$OFFSET, __spare0$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u16 __spare0[1]
     * }
     */
    public static void __spare0(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, __spare0$OFFSET, __spare0$LAYOUT.byteSize());
    }

    private static long[] __spare0$DIMS = { 1 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * __u16 __spare0[1]
     * }
     */
    public static long[] __spare0$dimensions() {
        return __spare0$DIMS;
    }
    private static final VarHandle __spare0$ELEM_HANDLE = __spare0$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * __u16 __spare0[1]
     * }
     */
    public static short __spare0(MemorySegment struct, long index0) {
        return (short)__spare0$ELEM_HANDLE.get(struct, __spare0$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * __u16 __spare0[1]
     * }
     */
    public static void __spare0(MemorySegment struct, long index0, short fieldValue) {
        __spare0$ELEM_HANDLE.set(struct, __spare0$OFFSET, index0, fieldValue);
    }

    private static final OfLong stx_ino$LAYOUT = (OfLong)$LAYOUT.select(groupElement("stx_ino"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 stx_ino
     * }
     */
    public static final OfLong stx_ino$layout() {
        return stx_ino$LAYOUT;
    }

    private static final long stx_ino$OFFSET = $LAYOUT.byteOffset(groupElement("stx_ino"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 stx_ino
     * }
     */
    public static final long stx_ino$offset() {
        return stx_ino$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 stx_ino
     * }
     */
    public static long stx_ino(MemorySegment struct) {
        return struct.get(stx_ino$LAYOUT, stx_ino$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 stx_ino
     * }
     */
    public static void stx_ino(MemorySegment struct, long fieldValue) {
        struct.set(stx_ino$LAYOUT, stx_ino$OFFSET, fieldValue);
    }

    private static final OfLong stx_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("stx_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 stx_size
     * }
     */
    public static final OfLong stx_size$layout() {
        return stx_size$LAYOUT;
    }

    private static final long stx_size$OFFSET = $LAYOUT.byteOffset(groupElement("stx_size"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 stx_size
     * }
     */
    public static final long stx_size$offset() {
        return stx_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 stx_size
     * }
     */
    public static long stx_size(MemorySegment struct) {
        return struct.get(stx_size$LAYOUT, stx_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 stx_size
     * }
     */
    public static void stx_size(MemorySegment struct, long fieldValue) {
        struct.set(stx_size$LAYOUT, stx_size$OFFSET, fieldValue);
    }

    private static final OfLong stx_blocks$LAYOUT = (OfLong)$LAYOUT.select(groupElement("stx_blocks"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 stx_blocks
     * }
     */
    public static final OfLong stx_blocks$layout() {
        return stx_blocks$LAYOUT;
    }

    private static final long stx_blocks$OFFSET = $LAYOUT.byteOffset(groupElement("stx_blocks"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 stx_blocks
     * }
     */
    public static final long stx_blocks$offset() {
        return stx_blocks$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 stx_blocks
     * }
     */
    public static long stx_blocks(MemorySegment struct) {
        return struct.get(stx_blocks$LAYOUT, stx_blocks$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 stx_blocks
     * }
     */
    public static void stx_blocks(MemorySegment struct, long fieldValue) {
        struct.set(stx_blocks$LAYOUT, stx_blocks$OFFSET, fieldValue);
    }

    private static final OfLong stx_attributes_mask$LAYOUT = (OfLong)$LAYOUT.select(groupElement("stx_attributes_mask"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 stx_attributes_mask
     * }
     */
    public static final OfLong stx_attributes_mask$layout() {
        return stx_attributes_mask$LAYOUT;
    }

    private static final long stx_attributes_mask$OFFSET = $LAYOUT.byteOffset(groupElement("stx_attributes_mask"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 stx_attributes_mask
     * }
     */
    public static final long stx_attributes_mask$offset() {
        return stx_attributes_mask$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 stx_attributes_mask
     * }
     */
    public static long stx_attributes_mask(MemorySegment struct) {
        return struct.get(stx_attributes_mask$LAYOUT, stx_attributes_mask$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 stx_attributes_mask
     * }
     */
    public static void stx_attributes_mask(MemorySegment struct, long fieldValue) {
        struct.set(stx_attributes_mask$LAYOUT, stx_attributes_mask$OFFSET, fieldValue);
    }

    private static final GroupLayout stx_atime$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("stx_atime"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct statx_timestamp stx_atime
     * }
     */
    public static final GroupLayout stx_atime$layout() {
        return stx_atime$LAYOUT;
    }

    private static final long stx_atime$OFFSET = $LAYOUT.byteOffset(groupElement("stx_atime"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct statx_timestamp stx_atime
     * }
     */
    public static final long stx_atime$offset() {
        return stx_atime$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct statx_timestamp stx_atime
     * }
     */
    public static MemorySegment stx_atime(MemorySegment struct) {
        return struct.asSlice(stx_atime$OFFSET, stx_atime$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct statx_timestamp stx_atime
     * }
     */
    public static void stx_atime(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, stx_atime$OFFSET, stx_atime$LAYOUT.byteSize());
    }

    private static final GroupLayout stx_btime$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("stx_btime"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct statx_timestamp stx_btime
     * }
     */
    public static final GroupLayout stx_btime$layout() {
        return stx_btime$LAYOUT;
    }

    private static final long stx_btime$OFFSET = $LAYOUT.byteOffset(groupElement("stx_btime"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct statx_timestamp stx_btime
     * }
     */
    public static final long stx_btime$offset() {
        return stx_btime$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct statx_timestamp stx_btime
     * }
     */
    public static MemorySegment stx_btime(MemorySegment struct) {
        return struct.asSlice(stx_btime$OFFSET, stx_btime$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct statx_timestamp stx_btime
     * }
     */
    public static void stx_btime(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, stx_btime$OFFSET, stx_btime$LAYOUT.byteSize());
    }

    private static final GroupLayout stx_ctime$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("stx_ctime"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct statx_timestamp stx_ctime
     * }
     */
    public static final GroupLayout stx_ctime$layout() {
        return stx_ctime$LAYOUT;
    }

    private static final long stx_ctime$OFFSET = $LAYOUT.byteOffset(groupElement("stx_ctime"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct statx_timestamp stx_ctime
     * }
     */
    public static final long stx_ctime$offset() {
        return stx_ctime$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct statx_timestamp stx_ctime
     * }
     */
    public static MemorySegment stx_ctime(MemorySegment struct) {
        return struct.asSlice(stx_ctime$OFFSET, stx_ctime$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct statx_timestamp stx_ctime
     * }
     */
    public static void stx_ctime(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, stx_ctime$OFFSET, stx_ctime$LAYOUT.byteSize());
    }

    private static final GroupLayout stx_mtime$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("stx_mtime"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct statx_timestamp stx_mtime
     * }
     */
    public static final GroupLayout stx_mtime$layout() {
        return stx_mtime$LAYOUT;
    }

    private static final long stx_mtime$OFFSET = $LAYOUT.byteOffset(groupElement("stx_mtime"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct statx_timestamp stx_mtime
     * }
     */
    public static final long stx_mtime$offset() {
        return stx_mtime$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct statx_timestamp stx_mtime
     * }
     */
    public static MemorySegment stx_mtime(MemorySegment struct) {
        return struct.asSlice(stx_mtime$OFFSET, stx_mtime$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct statx_timestamp stx_mtime
     * }
     */
    public static void stx_mtime(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, stx_mtime$OFFSET, stx_mtime$LAYOUT.byteSize());
    }

    private static final OfInt stx_rdev_major$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stx_rdev_major"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 stx_rdev_major
     * }
     */
    public static final OfInt stx_rdev_major$layout() {
        return stx_rdev_major$LAYOUT;
    }

    private static final long stx_rdev_major$OFFSET = $LAYOUT.byteOffset(groupElement("stx_rdev_major"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 stx_rdev_major
     * }
     */
    public static final long stx_rdev_major$offset() {
        return stx_rdev_major$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 stx_rdev_major
     * }
     */
    public static int stx_rdev_major(MemorySegment struct) {
        return struct.get(stx_rdev_major$LAYOUT, stx_rdev_major$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 stx_rdev_major
     * }
     */
    public static void stx_rdev_major(MemorySegment struct, int fieldValue) {
        struct.set(stx_rdev_major$LAYOUT, stx_rdev_major$OFFSET, fieldValue);
    }

    private static final OfInt stx_rdev_minor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stx_rdev_minor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 stx_rdev_minor
     * }
     */
    public static final OfInt stx_rdev_minor$layout() {
        return stx_rdev_minor$LAYOUT;
    }

    private static final long stx_rdev_minor$OFFSET = $LAYOUT.byteOffset(groupElement("stx_rdev_minor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 stx_rdev_minor
     * }
     */
    public static final long stx_rdev_minor$offset() {
        return stx_rdev_minor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 stx_rdev_minor
     * }
     */
    public static int stx_rdev_minor(MemorySegment struct) {
        return struct.get(stx_rdev_minor$LAYOUT, stx_rdev_minor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 stx_rdev_minor
     * }
     */
    public static void stx_rdev_minor(MemorySegment struct, int fieldValue) {
        struct.set(stx_rdev_minor$LAYOUT, stx_rdev_minor$OFFSET, fieldValue);
    }

    private static final OfInt stx_dev_major$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stx_dev_major"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 stx_dev_major
     * }
     */
    public static final OfInt stx_dev_major$layout() {
        return stx_dev_major$LAYOUT;
    }

    private static final long stx_dev_major$OFFSET = $LAYOUT.byteOffset(groupElement("stx_dev_major"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 stx_dev_major
     * }
     */
    public static final long stx_dev_major$offset() {
        return stx_dev_major$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 stx_dev_major
     * }
     */
    public static int stx_dev_major(MemorySegment struct) {
        return struct.get(stx_dev_major$LAYOUT, stx_dev_major$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 stx_dev_major
     * }
     */
    public static void stx_dev_major(MemorySegment struct, int fieldValue) {
        struct.set(stx_dev_major$LAYOUT, stx_dev_major$OFFSET, fieldValue);
    }

    private static final OfInt stx_dev_minor$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stx_dev_minor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 stx_dev_minor
     * }
     */
    public static final OfInt stx_dev_minor$layout() {
        return stx_dev_minor$LAYOUT;
    }

    private static final long stx_dev_minor$OFFSET = $LAYOUT.byteOffset(groupElement("stx_dev_minor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 stx_dev_minor
     * }
     */
    public static final long stx_dev_minor$offset() {
        return stx_dev_minor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 stx_dev_minor
     * }
     */
    public static int stx_dev_minor(MemorySegment struct) {
        return struct.get(stx_dev_minor$LAYOUT, stx_dev_minor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 stx_dev_minor
     * }
     */
    public static void stx_dev_minor(MemorySegment struct, int fieldValue) {
        struct.set(stx_dev_minor$LAYOUT, stx_dev_minor$OFFSET, fieldValue);
    }

    private static final OfLong stx_mnt_id$LAYOUT = (OfLong)$LAYOUT.select(groupElement("stx_mnt_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 stx_mnt_id
     * }
     */
    public static final OfLong stx_mnt_id$layout() {
        return stx_mnt_id$LAYOUT;
    }

    private static final long stx_mnt_id$OFFSET = $LAYOUT.byteOffset(groupElement("stx_mnt_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 stx_mnt_id
     * }
     */
    public static final long stx_mnt_id$offset() {
        return stx_mnt_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 stx_mnt_id
     * }
     */
    public static long stx_mnt_id(MemorySegment struct) {
        return struct.get(stx_mnt_id$LAYOUT, stx_mnt_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 stx_mnt_id
     * }
     */
    public static void stx_mnt_id(MemorySegment struct, long fieldValue) {
        struct.set(stx_mnt_id$LAYOUT, stx_mnt_id$OFFSET, fieldValue);
    }

    private static final OfInt stx_dio_mem_align$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stx_dio_mem_align"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 stx_dio_mem_align
     * }
     */
    public static final OfInt stx_dio_mem_align$layout() {
        return stx_dio_mem_align$LAYOUT;
    }

    private static final long stx_dio_mem_align$OFFSET = $LAYOUT.byteOffset(groupElement("stx_dio_mem_align"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 stx_dio_mem_align
     * }
     */
    public static final long stx_dio_mem_align$offset() {
        return stx_dio_mem_align$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 stx_dio_mem_align
     * }
     */
    public static int stx_dio_mem_align(MemorySegment struct) {
        return struct.get(stx_dio_mem_align$LAYOUT, stx_dio_mem_align$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 stx_dio_mem_align
     * }
     */
    public static void stx_dio_mem_align(MemorySegment struct, int fieldValue) {
        struct.set(stx_dio_mem_align$LAYOUT, stx_dio_mem_align$OFFSET, fieldValue);
    }

    private static final OfInt stx_dio_offset_align$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stx_dio_offset_align"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 stx_dio_offset_align
     * }
     */
    public static final OfInt stx_dio_offset_align$layout() {
        return stx_dio_offset_align$LAYOUT;
    }

    private static final long stx_dio_offset_align$OFFSET = $LAYOUT.byteOffset(groupElement("stx_dio_offset_align"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 stx_dio_offset_align
     * }
     */
    public static final long stx_dio_offset_align$offset() {
        return stx_dio_offset_align$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 stx_dio_offset_align
     * }
     */
    public static int stx_dio_offset_align(MemorySegment struct) {
        return struct.get(stx_dio_offset_align$LAYOUT, stx_dio_offset_align$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 stx_dio_offset_align
     * }
     */
    public static void stx_dio_offset_align(MemorySegment struct, int fieldValue) {
        struct.set(stx_dio_offset_align$LAYOUT, stx_dio_offset_align$OFFSET, fieldValue);
    }

    private static final OfLong stx_subvol$LAYOUT = (OfLong)$LAYOUT.select(groupElement("stx_subvol"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 stx_subvol
     * }
     */
    public static final OfLong stx_subvol$layout() {
        return stx_subvol$LAYOUT;
    }

    private static final long stx_subvol$OFFSET = $LAYOUT.byteOffset(groupElement("stx_subvol"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 stx_subvol
     * }
     */
    public static final long stx_subvol$offset() {
        return stx_subvol$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 stx_subvol
     * }
     */
    public static long stx_subvol(MemorySegment struct) {
        return struct.get(stx_subvol$LAYOUT, stx_subvol$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 stx_subvol
     * }
     */
    public static void stx_subvol(MemorySegment struct, long fieldValue) {
        struct.set(stx_subvol$LAYOUT, stx_subvol$OFFSET, fieldValue);
    }

    private static final OfInt stx_atomic_write_unit_min$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stx_atomic_write_unit_min"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 stx_atomic_write_unit_min
     * }
     */
    public static final OfInt stx_atomic_write_unit_min$layout() {
        return stx_atomic_write_unit_min$LAYOUT;
    }

    private static final long stx_atomic_write_unit_min$OFFSET = $LAYOUT.byteOffset(groupElement("stx_atomic_write_unit_min"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 stx_atomic_write_unit_min
     * }
     */
    public static final long stx_atomic_write_unit_min$offset() {
        return stx_atomic_write_unit_min$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 stx_atomic_write_unit_min
     * }
     */
    public static int stx_atomic_write_unit_min(MemorySegment struct) {
        return struct.get(stx_atomic_write_unit_min$LAYOUT, stx_atomic_write_unit_min$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 stx_atomic_write_unit_min
     * }
     */
    public static void stx_atomic_write_unit_min(MemorySegment struct, int fieldValue) {
        struct.set(stx_atomic_write_unit_min$LAYOUT, stx_atomic_write_unit_min$OFFSET, fieldValue);
    }

    private static final OfInt stx_atomic_write_unit_max$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stx_atomic_write_unit_max"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 stx_atomic_write_unit_max
     * }
     */
    public static final OfInt stx_atomic_write_unit_max$layout() {
        return stx_atomic_write_unit_max$LAYOUT;
    }

    private static final long stx_atomic_write_unit_max$OFFSET = $LAYOUT.byteOffset(groupElement("stx_atomic_write_unit_max"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 stx_atomic_write_unit_max
     * }
     */
    public static final long stx_atomic_write_unit_max$offset() {
        return stx_atomic_write_unit_max$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 stx_atomic_write_unit_max
     * }
     */
    public static int stx_atomic_write_unit_max(MemorySegment struct) {
        return struct.get(stx_atomic_write_unit_max$LAYOUT, stx_atomic_write_unit_max$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 stx_atomic_write_unit_max
     * }
     */
    public static void stx_atomic_write_unit_max(MemorySegment struct, int fieldValue) {
        struct.set(stx_atomic_write_unit_max$LAYOUT, stx_atomic_write_unit_max$OFFSET, fieldValue);
    }

    private static final OfInt stx_atomic_write_segments_max$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stx_atomic_write_segments_max"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 stx_atomic_write_segments_max
     * }
     */
    public static final OfInt stx_atomic_write_segments_max$layout() {
        return stx_atomic_write_segments_max$LAYOUT;
    }

    private static final long stx_atomic_write_segments_max$OFFSET = $LAYOUT.byteOffset(groupElement("stx_atomic_write_segments_max"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 stx_atomic_write_segments_max
     * }
     */
    public static final long stx_atomic_write_segments_max$offset() {
        return stx_atomic_write_segments_max$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 stx_atomic_write_segments_max
     * }
     */
    public static int stx_atomic_write_segments_max(MemorySegment struct) {
        return struct.get(stx_atomic_write_segments_max$LAYOUT, stx_atomic_write_segments_max$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 stx_atomic_write_segments_max
     * }
     */
    public static void stx_atomic_write_segments_max(MemorySegment struct, int fieldValue) {
        struct.set(stx_atomic_write_segments_max$LAYOUT, stx_atomic_write_segments_max$OFFSET, fieldValue);
    }

    private static final OfInt stx_dio_read_offset_align$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stx_dio_read_offset_align"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 stx_dio_read_offset_align
     * }
     */
    public static final OfInt stx_dio_read_offset_align$layout() {
        return stx_dio_read_offset_align$LAYOUT;
    }

    private static final long stx_dio_read_offset_align$OFFSET = $LAYOUT.byteOffset(groupElement("stx_dio_read_offset_align"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 stx_dio_read_offset_align
     * }
     */
    public static final long stx_dio_read_offset_align$offset() {
        return stx_dio_read_offset_align$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 stx_dio_read_offset_align
     * }
     */
    public static int stx_dio_read_offset_align(MemorySegment struct) {
        return struct.get(stx_dio_read_offset_align$LAYOUT, stx_dio_read_offset_align$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 stx_dio_read_offset_align
     * }
     */
    public static void stx_dio_read_offset_align(MemorySegment struct, int fieldValue) {
        struct.set(stx_dio_read_offset_align$LAYOUT, stx_dio_read_offset_align$OFFSET, fieldValue);
    }

    private static final OfInt stx_atomic_write_unit_max_opt$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stx_atomic_write_unit_max_opt"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 stx_atomic_write_unit_max_opt
     * }
     */
    public static final OfInt stx_atomic_write_unit_max_opt$layout() {
        return stx_atomic_write_unit_max_opt$LAYOUT;
    }

    private static final long stx_atomic_write_unit_max_opt$OFFSET = $LAYOUT.byteOffset(groupElement("stx_atomic_write_unit_max_opt"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 stx_atomic_write_unit_max_opt
     * }
     */
    public static final long stx_atomic_write_unit_max_opt$offset() {
        return stx_atomic_write_unit_max_opt$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 stx_atomic_write_unit_max_opt
     * }
     */
    public static int stx_atomic_write_unit_max_opt(MemorySegment struct) {
        return struct.get(stx_atomic_write_unit_max_opt$LAYOUT, stx_atomic_write_unit_max_opt$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 stx_atomic_write_unit_max_opt
     * }
     */
    public static void stx_atomic_write_unit_max_opt(MemorySegment struct, int fieldValue) {
        struct.set(stx_atomic_write_unit_max_opt$LAYOUT, stx_atomic_write_unit_max_opt$OFFSET, fieldValue);
    }

    private static final SequenceLayout __spare2$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("__spare2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u32 __spare2[1]
     * }
     */
    public static final SequenceLayout __spare2$layout() {
        return __spare2$LAYOUT;
    }

    private static final long __spare2$OFFSET = $LAYOUT.byteOffset(groupElement("__spare2"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u32 __spare2[1]
     * }
     */
    public static final long __spare2$offset() {
        return __spare2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u32 __spare2[1]
     * }
     */
    public static MemorySegment __spare2(MemorySegment struct) {
        return struct.asSlice(__spare2$OFFSET, __spare2$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u32 __spare2[1]
     * }
     */
    public static void __spare2(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, __spare2$OFFSET, __spare2$LAYOUT.byteSize());
    }

    private static long[] __spare2$DIMS = { 1 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * __u32 __spare2[1]
     * }
     */
    public static long[] __spare2$dimensions() {
        return __spare2$DIMS;
    }
    private static final VarHandle __spare2$ELEM_HANDLE = __spare2$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * __u32 __spare2[1]
     * }
     */
    public static int __spare2(MemorySegment struct, long index0) {
        return (int)__spare2$ELEM_HANDLE.get(struct, __spare2$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * __u32 __spare2[1]
     * }
     */
    public static void __spare2(MemorySegment struct, long index0, int fieldValue) {
        __spare2$ELEM_HANDLE.set(struct, __spare2$OFFSET, index0, fieldValue);
    }

    private static final SequenceLayout __spare3$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("__spare3"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * __u64 __spare3[8]
     * }
     */
    public static final SequenceLayout __spare3$layout() {
        return __spare3$LAYOUT;
    }

    private static final long __spare3$OFFSET = $LAYOUT.byteOffset(groupElement("__spare3"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * __u64 __spare3[8]
     * }
     */
    public static final long __spare3$offset() {
        return __spare3$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * __u64 __spare3[8]
     * }
     */
    public static MemorySegment __spare3(MemorySegment struct) {
        return struct.asSlice(__spare3$OFFSET, __spare3$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * __u64 __spare3[8]
     * }
     */
    public static void __spare3(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, __spare3$OFFSET, __spare3$LAYOUT.byteSize());
    }

    private static long[] __spare3$DIMS = { 8 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * __u64 __spare3[8]
     * }
     */
    public static long[] __spare3$dimensions() {
        return __spare3$DIMS;
    }
    private static final VarHandle __spare3$ELEM_HANDLE = __spare3$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * __u64 __spare3[8]
     * }
     */
    public static long __spare3(MemorySegment struct, long index0) {
        return (long)__spare3$ELEM_HANDLE.get(struct, __spare3$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * __u64 __spare3[8]
     * }
     */
    public static void __spare3(MemorySegment struct, long index0, long fieldValue) {
        __spare3$ELEM_HANDLE.set(struct, __spare3$OFFSET, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

