// Generated by jextract

package com.microsoft;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _FILETIME {
 *     DWORD dwLowDateTime;
 *     DWORD dwHighDateTime;
 * } FILETIME
 * }
 */
public class FILETIME extends _FILETIME {

    FILETIME() {
        // Should not be called directly
    }
}

