// Generated by jextract

package com.microsoft;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _WIN32_FIND_DATAW {
 *     DWORD dwFileAttributes;
 *     FILETIME ftCreationTime;
 *     FILETIME ftLastAccessTime;
 *     FILETIME ftLastWriteTime;
 *     DWORD nFileSizeHigh;
 *     DWORD nFileSizeLow;
 *     DWORD dwReserved0;
 *     DWORD dwReserved1;
 *     WCHAR cFileName[260];
 *     WCHAR cAlternateFileName[14];
 * } WIN32_FIND_DATAW
 * }
 */
public class WIN32_FIND_DATAW extends _WIN32_FIND_DATAW {

    WIN32_FIND_DATAW() {
        // Should not be called directly
    }
}

