// Generated by jextract

package com.microsoft;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class Windows extends Windows$shared {

    Windows() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.libraryLookup(System.mapLibraryName("kernel32"), LIBRARY_ARENA)
            .or(SymbolLookup.loaderLookup())
            .or(Linker.nativeLinker().defaultLookup());

    private static final int FILE_ATTRIBUTE_READONLY = (int)1L;
    /**
     * {@snippet lang=c :
     * #define FILE_ATTRIBUTE_READONLY 1
     * }
     */
    public static int FILE_ATTRIBUTE_READONLY() {
        return FILE_ATTRIBUTE_READONLY;
    }
    private static final int FILE_ATTRIBUTE_HIDDEN = (int)2L;
    /**
     * {@snippet lang=c :
     * #define FILE_ATTRIBUTE_HIDDEN 2
     * }
     */
    public static int FILE_ATTRIBUTE_HIDDEN() {
        return FILE_ATTRIBUTE_HIDDEN;
    }
    private static final int FILE_ATTRIBUTE_DIRECTORY = (int)16L;
    /**
     * {@snippet lang=c :
     * #define FILE_ATTRIBUTE_DIRECTORY 16
     * }
     */
    public static int FILE_ATTRIBUTE_DIRECTORY() {
        return FILE_ATTRIBUTE_DIRECTORY;
    }
    private static final int FILE_ATTRIBUTE_ARCHIVE = (int)32L;
    /**
     * {@snippet lang=c :
     * #define FILE_ATTRIBUTE_ARCHIVE 32
     * }
     */
    public static int FILE_ATTRIBUTE_ARCHIVE() {
        return FILE_ATTRIBUTE_ARCHIVE;
    }
    private static final int FILE_ATTRIBUTE_NORMAL = (int)128L;
    /**
     * {@snippet lang=c :
     * #define FILE_ATTRIBUTE_NORMAL 128
     * }
     */
    public static int FILE_ATTRIBUTE_NORMAL() {
        return FILE_ATTRIBUTE_NORMAL;
    }
    private static final int FILE_ATTRIBUTE_REPARSE_POINT = (int)1024L;
    /**
     * {@snippet lang=c :
     * #define FILE_ATTRIBUTE_REPARSE_POINT 1024
     * }
     */
    public static int FILE_ATTRIBUTE_REPARSE_POINT() {
        return FILE_ATTRIBUTE_REPARSE_POINT;
    }

    private static class FindClose {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Windows.C_INT,
            Windows.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("FindClose");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * BOOL FindClose(HANDLE hFindFile)
     * }
     */
    public static FunctionDescriptor FindClose$descriptor() {
        return FindClose.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * BOOL FindClose(HANDLE hFindFile)
     * }
     */
    public static MethodHandle FindClose$handle() {
        return FindClose.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * BOOL FindClose(HANDLE hFindFile)
     * }
     */
    public static MemorySegment FindClose$address() {
        return FindClose.ADDR;
    }

    /**
     * {@snippet lang=c :
     * BOOL FindClose(HANDLE hFindFile)
     * }
     */
    public static int FindClose(MemorySegment hFindFile) {
        var mh$ = FindClose.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("FindClose", hFindFile);
            }
            return (int)mh$.invokeExact(hFindFile);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class FindFirstFileW {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Windows.C_POINTER,
            Windows.C_POINTER,
            Windows.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("FindFirstFileW");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * HANDLE FindFirstFileW(LPCWSTR lpFileName, LPWIN32_FIND_DATAW lpFindFileData)
     * }
     */
    public static FunctionDescriptor FindFirstFileW$descriptor() {
        return FindFirstFileW.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * HANDLE FindFirstFileW(LPCWSTR lpFileName, LPWIN32_FIND_DATAW lpFindFileData)
     * }
     */
    public static MethodHandle FindFirstFileW$handle() {
        return FindFirstFileW.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * HANDLE FindFirstFileW(LPCWSTR lpFileName, LPWIN32_FIND_DATAW lpFindFileData)
     * }
     */
    public static MemorySegment FindFirstFileW$address() {
        return FindFirstFileW.ADDR;
    }

    /**
     * {@snippet lang=c :
     * HANDLE FindFirstFileW(LPCWSTR lpFileName, LPWIN32_FIND_DATAW lpFindFileData)
     * }
     */
    public static MemorySegment FindFirstFileW(MemorySegment lpFileName, MemorySegment lpFindFileData) {
        var mh$ = FindFirstFileW.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("FindFirstFileW", lpFileName, lpFindFileData);
            }
            return (MemorySegment)mh$.invokeExact(lpFileName, lpFindFileData);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class GetFileAttributesW {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Windows.C_LONG,
            Windows.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("GetFileAttributesW");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * DWORD GetFileAttributesW(LPCWSTR lpFileName)
     * }
     */
    public static FunctionDescriptor GetFileAttributesW$descriptor() {
        return GetFileAttributesW.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * DWORD GetFileAttributesW(LPCWSTR lpFileName)
     * }
     */
    public static MethodHandle GetFileAttributesW$handle() {
        return GetFileAttributesW.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * DWORD GetFileAttributesW(LPCWSTR lpFileName)
     * }
     */
    public static MemorySegment GetFileAttributesW$address() {
        return GetFileAttributesW.ADDR;
    }

    /**
     * {@snippet lang=c :
     * DWORD GetFileAttributesW(LPCWSTR lpFileName)
     * }
     */
    public static int GetFileAttributesW(MemorySegment lpFileName) {
        var mh$ = GetFileAttributesW.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("GetFileAttributesW", lpFileName);
            }
            return (int)mh$.invokeExact(lpFileName);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class GetShortPathNameW {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Windows.C_LONG,
            Windows.C_POINTER,
            Windows.C_POINTER,
            Windows.C_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("GetShortPathNameW");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * DWORD GetShortPathNameW(LPCWSTR lpszLongPath, LPWSTR lpszShortPath, DWORD cchBuffer)
     * }
     */
    public static FunctionDescriptor GetShortPathNameW$descriptor() {
        return GetShortPathNameW.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * DWORD GetShortPathNameW(LPCWSTR lpszLongPath, LPWSTR lpszShortPath, DWORD cchBuffer)
     * }
     */
    public static MethodHandle GetShortPathNameW$handle() {
        return GetShortPathNameW.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * DWORD GetShortPathNameW(LPCWSTR lpszLongPath, LPWSTR lpszShortPath, DWORD cchBuffer)
     * }
     */
    public static MemorySegment GetShortPathNameW$address() {
        return GetShortPathNameW.ADDR;
    }

    /**
     * {@snippet lang=c :
     * DWORD GetShortPathNameW(LPCWSTR lpszLongPath, LPWSTR lpszShortPath, DWORD cchBuffer)
     * }
     */
    public static int GetShortPathNameW(MemorySegment lpszLongPath, MemorySegment lpszShortPath, int cchBuffer) {
        var mh$ = GetShortPathNameW.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("GetShortPathNameW", lpszLongPath, lpszShortPath, cchBuffer);
            }
            return (int)mh$.invokeExact(lpszLongPath, lpszShortPath, cchBuffer);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class SetFileAttributesW {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Windows.C_INT,
            Windows.C_POINTER,
            Windows.C_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("SetFileAttributesW");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * BOOL SetFileAttributesW(LPCWSTR lpFileName, DWORD dwFileAttributes)
     * }
     */
    public static FunctionDescriptor SetFileAttributesW$descriptor() {
        return SetFileAttributesW.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * BOOL SetFileAttributesW(LPCWSTR lpFileName, DWORD dwFileAttributes)
     * }
     */
    public static MethodHandle SetFileAttributesW$handle() {
        return SetFileAttributesW.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * BOOL SetFileAttributesW(LPCWSTR lpFileName, DWORD dwFileAttributes)
     * }
     */
    public static MemorySegment SetFileAttributesW$address() {
        return SetFileAttributesW.ADDR;
    }

    /**
     * {@snippet lang=c :
     * BOOL SetFileAttributesW(LPCWSTR lpFileName, DWORD dwFileAttributes)
     * }
     */
    public static int SetFileAttributesW(MemorySegment lpFileName, int dwFileAttributes) {
        var mh$ = SetFileAttributesW.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("SetFileAttributesW", lpFileName, dwFileAttributes);
            }
            return (int)mh$.invokeExact(lpFileName, dwFileAttributes);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class GetLastError {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Windows.C_LONG    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("GetLastError");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * DWORD GetLastError()
     * }
     */
    public static FunctionDescriptor GetLastError$descriptor() {
        return GetLastError.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * DWORD GetLastError()
     * }
     */
    public static MethodHandle GetLastError$handle() {
        return GetLastError.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * DWORD GetLastError()
     * }
     */
    public static MemorySegment GetLastError$address() {
        return GetLastError.ADDR;
    }

    /**
     * {@snippet lang=c :
     * DWORD GetLastError()
     * }
     */
    public static int GetLastError() {
        var mh$ = GetLastError.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("GetLastError");
            }
            return (int)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final int MAXDWORD = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define MAXDWORD 4294967295
     * }
     */
    public static int MAXDWORD() {
        return MAXDWORD;
    }
    private static final int IO_REPARSE_TAG_SYMLINK = (int)2684354572L;
    /**
     * {@snippet lang=c :
     * #define IO_REPARSE_TAG_SYMLINK 2684354572
     * }
     */
    public static int IO_REPARSE_TAG_SYMLINK() {
        return IO_REPARSE_TAG_SYMLINK;
    }
    private static final int INVALID_FILE_ATTRIBUTES = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define INVALID_FILE_ATTRIBUTES 4294967295
     * }
     */
    public static int INVALID_FILE_ATTRIBUTES() {
        return INVALID_FILE_ATTRIBUTES;
    }
    private static final MemorySegment INVALID_HANDLE_VALUE = MemorySegment.ofAddress(-1L);
    /**
     * {@snippet lang=c :
     * #define INVALID_HANDLE_VALUE (void*) -1
     * }
     */
    public static MemorySegment INVALID_HANDLE_VALUE() {
        return INVALID_HANDLE_VALUE;
    }
    private static final int ERROR_FILE_NOT_FOUND = (int)2L;
    /**
     * {@snippet lang=c :
     * #define ERROR_FILE_NOT_FOUND 2
     * }
     */
    public static int ERROR_FILE_NOT_FOUND() {
        return ERROR_FILE_NOT_FOUND;
    }
    private static final int ERROR_PATH_NOT_FOUND = (int)3L;
    /**
     * {@snippet lang=c :
     * #define ERROR_PATH_NOT_FOUND 3
     * }
     */
    public static int ERROR_PATH_NOT_FOUND() {
        return ERROR_PATH_NOT_FOUND;
    }
}

