bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               introExampleContent.xml,\
               style.css,\
               about.html
src.includes = about.html

# Maven/Tycho build POM adjustments
pom.model.property.skipAPIAnalysis = true
