// Generated by jextract

package org.eclipse.core.internal.resources.refresh.linux.inotify;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$0 {

    static final FunctionDescriptor inotify_init$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle inotify_init$MH = RuntimeHelper.downcallHandle(
        "inotify_init",
        constants$0.inotify_init$FUNC, false
    );
    static final FunctionDescriptor inotify_init1$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle inotify_init1$MH = RuntimeHelper.downcallHandle(
        "inotify_init1",
        constants$0.inotify_init1$FUNC, false
    );
    static final FunctionDescriptor inotify_add_watch$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle inotify_add_watch$MH = RuntimeHelper.downcallHandle(
        "inotify_add_watch",
        constants$0.inotify_add_watch$FUNC, false
    );
    static final FunctionDescriptor inotify_rm_watch$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle inotify_rm_watch$MH = RuntimeHelper.downcallHandle(
        "inotify_rm_watch",
        constants$0.inotify_rm_watch$FUNC, false
    );
}


