/*******************************************************************************
 * Copyright (c) 2010 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
#include <jni.h>

/*
 * Get a null-terminated byte array from a java byte array. The returned bytearray
 * needs to be freed when not used anymore. Use free(result) to do that.
 */
jbyte* getByteArray(JNIEnv *, jbyteArray);

/*
 * Fills LinuxStructStat object with data from struct stat.
 */
jint convertStatToObject(JNIEnv *, struct stat, int errnoValue, jobject);

/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class org_eclipse_core_internal_filesystem_local_linux_LinuxFileNatives */

#ifndef _Included_org_eclipse_core_internal_filesystem_local_linux_LinuxFileNatives
#define _Included_org_eclipse_core_internal_filesystem_local_linux_LinuxFileNatives
#ifdef __cplusplus
extern "C" {
#endif
#undef org_eclipse_core_internal_filesystem_local_linux_LinuxFileNatives_ENOENT
#define org_eclipse_core_internal_filesystem_local_linux_LinuxFileNatives_ENOENT 2L
/*
 * Class:     org_eclipse_core_internal_filesystem_local_linux_LinuxFileNatives
 * Method:    initializeLinuxStructStatFieldIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_eclipse_core_internal_filesystem_local_linux_LinuxFileNatives_initializeLinuxStructStatFieldIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_eclipse_core_internal_filesystem_local_linux_LinuxFileNatives
 * Method:    chmod
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_org_eclipse_core_internal_filesystem_local_linux_LinuxFileNatives_chmod
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     org_eclipse_core_internal_filesystem_local_linux_LinuxFileNatives
 * Method:    stat
 * Signature: ([BLorg/eclipse/core/internal/filesystem/local/linux/LinuxStructStat;)I
 */
JNIEXPORT jint JNICALL Java_org_eclipse_core_internal_filesystem_local_linux_LinuxFileNatives_stat
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     org_eclipse_core_internal_filesystem_local_linux_LinuxFileNatives
 * Method:    lstat
 * Signature: ([BLorg/eclipse/core/internal/filesystem/local/linux/LinuxStructStat;)I
 */
JNIEXPORT jint JNICALL Java_org_eclipse_core_internal_filesystem_local_linux_LinuxFileNatives_lstat
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     org_eclipse_core_internal_filesystem_local_linux_LinuxFileNatives
 * Method:    readlink
 * Signature: ([B[BJ)I
 */
JNIEXPORT jint JNICALL Java_org_eclipse_core_internal_filesystem_local_linux_LinuxFileNatives_readlink
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jlong);

/*
 * Class:     org_eclipse_core_internal_filesystem_local_linux_LinuxFileNatives
 * Method:    getflag
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_eclipse_core_internal_filesystem_local_linux_LinuxFileNatives_getflag
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_eclipse_core_internal_filesystem_local_linux_LinuxFileNatives
 * Method:    listDir
 * Signature: ([B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_org_eclipse_core_internal_filesystem_local_linux_LinuxFileNatives_listDir
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_eclipse_core_internal_filesystem_local_linux_LinuxFileNatives
 * Method:    listDirAndGetFileInfos
 * Signature: ([B)[Lorg/eclipse/core/internal/filesystem/local/linux/LinuxStructStat;
 */
JNIEXPORT jobjectArray JNICALL Java_org_eclipse_core_internal_filesystem_local_linux_LinuxFileNatives_listDirAndGetFileInfos
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
